[DEFAULT]
debug = false
# Uncomment and replace with the address which should receive any error reports
#email_to = you@yourdomain.com
smtp_server = localhost
error_email_from = paste@localhost

[server:main]
use = egg:Paste#http
host = 0.0.0.0
port = 5000


[app:main]
#normally config:../ckan/test-core.ini but can't be for github actions docker container
use = config:/srv/app/src/ckan/test-core.ini

ckan.datastore.write_url = postgresql://datastore_write:pass@postgres/datastore_test
ckan.datastore.read_url = postgresql://datastore_read:pass@postgres/datastore_test
sqlalchemy.url = postgresql://ckan_default:pass@postgres/ckan_test
solr_url = http://solr:8983/solr/ckan
ckan.redis.url = redis://redis:6379/1

# Here we hard-code the database and a flag to make default tests
# run fast.
ckan.plugins = s3filestore
ckan.legacy_templates = false
# NB: other test configuration should go in test-core.ini, which is
#     what the postgres tests use.

ckanext.s3filestore.check_access_on_startup = false
#ckanext.s3filestore.aws_use_ami_role = True
ckanext.s3filestore.aws_access_key_id = access-key-id
ckanext.s3filestore.aws_secret_access_key = secret-key
ckanext.s3filestore.region_name = ap-southeast-2
ckanext.s3filestore.signature_version = s3v4
ckanext.s3filestore.addressing_style = path
ckanext.s3filestore.host_name = http://localhost:5000
ckanext.s3filestore.aws_bucket_name = my-bucket
ckanext.s3filestore.aws_storage_path = my-path
ckanext.s3filestore.filesystem_download_fallback = True

# Logging configuration
[loggers]
keys = root, ckan, sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_ckan]
qualname = ckan
handlers =
level = INFO

[logger_sqlalchemy]
handlers =
qualname = sqlalchemy.engine
level = WARN

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
