name: Continuous Integration
on: push

jobs:
  ci:
    name: Run continuous integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up environment matching TravisCI
        run: ./bin/travis-build.bash
        env:
          PGVERSION: 11
          CKAN_GIT_REPO: ckan/ckan
          CKAN_BRANCH: master

      - name: Run nosetests
        run: ./bin/travis-run.sh

      - name: Generate coverage report
        uses: coverallsapp/github-action@master
