name: Continuous Integration
on: push

jobs:
  continuous-integration-tests:
    name: Run continuous integration tests
    runs-on: ubuntu-18.04

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Start services
        run: |
          docker network create amazeeio-network
          docker-compose up -d --build --force-recreate

      - name: Run linter
        run: |
          docker cp -L .flake8 $(docker-compose ps -q ckan):/app/.
          docker exec -i $(docker-compose ps -q ckan) flake8 "${@:-/app/ckanext}"

      - name: Run unit tests
        run: |
          docker exec -i $(docker-compose ps -q ckan) \
          nosetests --ckan --nologcapture --with-pylons=/app/ckan/default/production.ini \
          --with-coverage --cover-package=ckanext.s3filestore --cover-inclusive --cover-erase --cover-tests
