name: Continuous Integration
on: push

jobs:
  continuous-integration-tests:
    name: Run continuous integration tests
    runs-on: ubuntu-18.04

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y containerd docker.io python-pip
          sudo pip install docker-compose moto[server] "pyrsistent<0.16.0" backports.ssl_match_hostname

      - name: Set up Docker containers
        run: |
          sudo systemctl unmask docker
          sudo systemctl start docker
          sudo docker-compose up -d --build --force-recreate

      - name: Start services
        run: |
          moto_server s3 &

      - name: Check out CKAN
        uses: actions/checkout@v2
        with:
          repository: ckan/ckan
          path: ckan
          ref: ckan-2.8.6

      - name: Install CKAN dependencies
        run: |
          cd ckan
          sudo pip install -r requirements.txt
          sudo pip install -r dev-requirements.txt
          sudo pip install -r requirement-setuptools.txt
          sudo python setup.py develop

      - name: Install CKAN extension dependencies
        run: |
          sudo python setup.py develop
          sudo pip install -r requirements.txt
          sudo pip install -r dev-requirements.txt

      - name: Setup database
        run: |
          cd ckan
          paster db init -c test-core.ini

      - name: Prepare test configuration
        run: |
          mkdir -p subdir
          cp test.ini subdir

      - name: Run unit tests
        run: nosetests --ckan --nologcapture --with-pylons=subdir/test.ini --with-coverage --cover-package=ckanext.s3filestore --cover-inclusive --cover-erase --cover-tests

      - name: Generate coverage report
        uses: coverallsapp/github-action@master
